### ISSUE TITLE
Question about the Equations in the paper

### ISSUE THREAD

**Issue by DongXiang-CV** [hbzju/PiCO#3]
非常感谢您的工作  我有个问题关于这个等式 希望您能解答

<img width="871" alt="image" src="https://user-images.githubusercontent.com/19317869/166475311-ea873c7d-f282-49f1-834a-e02767e349d4.png">

为什么我们可以把求和符号移到平方里面? 例如

(a-b)^{2}+(a-c)^{2} != (a- ((b+c)/2) )^{2}

**Comment by hbzju** [comment]
Hi!

The details of this derivation are shown in Appendix A. Btw, the left side of your example should be (a-b)^{2}+(a-c)^{2} + (b-c)^{2} since we use all example pairs in S_j.

Best.
