### ISSUE TITLE
Select positive samples

### ISSUE THREAD

**Issue by xiaomanzu** [hbzju/PiCO#7]
Hi, I noticed in the paper that positive samples for partial labels are selected based on predicting consistent labels. However, I couldn't find this specific code in the code.  Can you point it out for me? Instead, I observed that the code focuses on strong and weak augmentations of the same sample for positive and negative sample selection. I'm not sure if my understanding is correct. Can you please guide me on this? Thank you for your assistance.

**Comment by hbzju** [comment]
Hi! The code for selecting positive samples is at line 331, train.py:
`mask = torch.eq(pseudo_target_cont[:batch_size],  #pseudo_target_cont.T).float().cuda()`
I hope it helps.

**Comment by xiaomanzu** [comment]
Okay, I understand, thank you!!!
